# Generated by Django 4.2.7 on 2024-02-16 15:22

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to=api.models.guardar_hoteles)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.viaje')),
            ],
        ),
    ]
