# Generated by Django 5.0.2 on 2024-03-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='link_pago',
            field=models.URLField(blank=True, null=True),
        ),
    ]
