# Generated by Django 4.2.7 on 2024-01-23 01:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=api.models.upload_to),
        ),
    ]
