# Generated by Django 4.2.7 on 2024-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='no_incluye',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
