# Generated by Django 4.2.7 on 2024-01-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_etiqueta_destino_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='wa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='foo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destino',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='api.etiqueta'),
        ),
    ]
