export { default as Iniciar_sesion } from "./Iniciar_sesion/Iniciar_sesion"
export { default as Registrarse } from "./Registrarse/Registrarse"
export { default as TerminosYcondiciones } from "./TerminosYcondiciones/TerminosYcondiciones"
export { default as Inicio } from "./Inicio/Inicio"
export { default as ErrorPage } from "./ErrorPage/ErrorPage"
export { default as Contacto } from "./Contacto/Contacto"
